<a href="https://colab.research.google.com/github/kietietv/TH_Deep_Learning/blob/main/Tu%E1%BA%A7n_02_TH_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow

In [4]:
import tensorflow as tf
import numpy as np

### Bài 1: Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [ ]:
bài_1 = tf.zeros([2, 3])
print("Bài 1:\n", bài_1)

Bài 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### Bài 2: Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được gán 0

In [ ]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])

# Cách 1: Dùng zeros_like
bài_2_cách_1 = tf.zeros_like(X)

# Cách 2: Lấy thuộc tính của X
bài_2_cách_2 = tf.zeros(shape=X.shape, dtype=X.dtype)

print("Bài 2:\n", bài_2_cách_1)
print("Bài 2:\n", bài_2_cách_2)

Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


### Bài 3: Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [ ]:
bài_3 = tf.fill([3, 2], 5)
print("Bài 3:\n", bài_3)

Bài 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


### Bài 4: Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [7]:
even_values = np.random.choice([6, 8, 10], size=50, replace=True)

# 2. Chuyển từ numpy array sang tensorflow tensor
tensor_result = tf.constant(even_values, dtype=tf.int32)

print("Tensor 1-chiều với 50 phần tử chẵn:")
print(tensor_result)

Tensor 1-chiều với 50 phần tử chẵn:
tf.Tensor(
[10  6  8 10  6  6  8  8  6  8 10 10  8  6 10  8  8  6 10  8  6  6  6  8
 10  8 10  6 10  6  8  8 10  6  8  6  8  8  6  8  8  6  6  6  8  6  6 10
 10 10], shape=(50,), dtype=int32)


### Bài 5: Tạo một tensor 1-chiều có giá trị như [10, 12, 14, ..., 100]

In [ ]:
bài_5 = tf.range(start=10, limit=101, delta=2)
print("Bài 5:\n", bài_5)

Bài 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


### Bài 6: Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean = 0, stddev = 2

In [9]:
bài_6 = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print("Bài 6:\n", bài_6)

Bài 6:
 tf.Tensor(
[[ 2.42754     0.03234149]
 [ 3.3235548  -0.32347348]
 [-0.53566986  0.2782632 ]], shape=(3, 2), dtype=float32)


### Bài 7: Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi [0, 2]

In [ ]:
bài_7 = tf.random.uniform(shape=[3, 2], minval=0.0, maxval=2.0)
print("Bài 7:\n", bài_7)

Bài 7:
 tf.Tensor(
[[0.16715908 0.4889698 ]
 [0.11441374 1.3186653 ]
 [0.4772315  1.6878088 ]], shape=(3, 2), dtype=float32)


### Bài 8: Xáo trộn (Shuffle) Tensor X theo chiều thứ nhất

In [ ]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])

bài_8 = tf.random.shuffle(X)
print("Bài 8 (Kết quả sau khi shuffle hàng):\n", bài_8.numpy())

Bài 8 (Kết quả sau khi shuffle hàng):
 [[3 4]
 [5 6]
 [1 2]]


### Bài 9: Khởi tạo và cắt ngẫu nhiên Tensor (Random Crop)

In [11]:
# Tạo ngẫu nhiên một tensor giả lập ảnh kích thước (10, 10, 3)
tensor_3d = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=255, dtype=tf.int32)

# Cắt ngẫu nhiên một vùng kích thước (5, 5, 3)
bài_9 = tf.image.random_crop(tensor_3d, size=[5, 5, 3])
print("Bài 9 - Kích thước tensor sau khi cắt:", bài_9)

Bài 9 - Kích thước tensor sau khi cắt: tf.Tensor(
[[[239 145 133]
  [245  66  30]
  [250  67 201]
  [188 202  61]
  [ 48  66  63]]

 [[210 154   7]
  [214 126  85]
  [ 35 198 222]
  [143 201  41]
  [127 162 234]]

 [[216  95 102]
  [200  60 239]
  [  4 175  65]
  [228   1 149]
  [ 26  52  37]]

 [[188  16  95]
  [193  17 120]
  [137  49  75]
  [ 26  43 241]
  [ 67  84 161]]

 [[ 92 248 170]
  [121  50 136]
  [253 115 106]
  [ 93 252 193]
  [ 52 194  83]]], shape=(5, 5, 3), dtype=int32)


### Bài 10: Phép toán điều kiện trên phần tử (Element-wise Condition)

In [ ]:
x = tf.random.uniform(shape=[5], minval=1, maxval=10, dtype=tf.int32)
y = tf.random.uniform(shape=[5], minval=1, maxval=10, dtype=tf.int32)

# Tạo ma trận điều kiện so sánh phần tử
điều_kiện = x < y

# Nếu điều kiện Đúng chọn (x + y), ngược lại chọn (x - y)
bài_10 = tf.where(điều_kiện, x + y, x - y)

print("Tensor x: ", x.numpy())
print("Tensor y: ", y.numpy())
print("Kết quả : ", bài_10.numpy())

Tensor x:  [6 4 7 9 4]
Tensor y:  [5 7 6 4 1]
Kết quả :  [ 1 11  1  5  3]


### Bài 11: Cộng ma trận và giữ nguyên giá trị đường chéo gốc

In [ ]:
# Điều chỉnh kích thước thành (3, 3) để phép toán đường chéo hợp lệ
x = tf.random.uniform(shape=(3, 3), minval=5, maxval=10, dtype=tf.int32)
y = tf.random.uniform(shape=(3, 3), minval=15, maxval=20, dtype=tf.int32)

# Thực hiện phép cộng x + y
tong_xy = x + y

# Lấy các phần tử trên đường chéo chính của x
duong_cheo_x = tf.linalg.diag_part(x)

# Khôi phục đường chéo chính của x vào ma trận tổng
bài_11 = tf.linalg.set_diag(tong_xy, duong_cheo_x)

print("Ma trận x ban đầu:\n", x.numpy())
print("Ma trận tổng x + y ban đầu:\n", tong_xy.numpy())
print("Kết quả sau khi giữ lại đường chéo của x:\n", bài_11.numpy())

Ma trận x ban đầu:
 [[8 7 8]
 [8 5 9]
 [7 9 5]]
Ma trận tổng x + y ban đầu:
 [[26 25 25]
 [27 21 24]
 [23 26 23]]
Kết quả sau khi giữ lại đường chéo của x:
 [[ 8 25 25]
 [27  5 24]
 [23 26  5]]


### Bài 12: Đóng gói các hàm tính toán vào môi trường Graph Execution

In [14]:
# Dùng decorator biên dịch hàm chạy trên Graph của TensorFlow
@tf.function
def tinh_toan_tren_graph(tensor_a, tensor_b):
    cong = tf.add(tensor_a, tensor_b)
    tru = tf.subtract(tensor_a, tensor_b)
    nhan = tf.multiply(tensor_a, tensor_b)
    chia = tf.divide(tensor_a, tensor_b)
    return cong, tru, nhan, chia

# Khởi tạo 2 tensor ngẫu nhiên kích thước (3, 2, 2)
x = tf.random.normal(shape=(3, 2, 2))
y = tf.random.normal(shape=(3, 2, 2))

# Gọi hàm chạy trực tiếp trong Graph
kq_cong, kq_tru, kq_nhan, kq_chia = tinh_toan_tren_graph(x, y)

print("Đã thực thi tính toán Cộng, Trừ, Nhân, Chia trên Graph thành công!")
print("Kết quả phép cộng: ", kq_cong)

Đã thực thi tính toán Cộng, Trừ, Nhân, Chia trên Graph thành công!
Kết quả phép cộng:  tf.Tensor(
[[[-0.24711883 -0.9239302 ]
  [-1.7160971   1.0024904 ]]

 [[ 3.0563517  -2.283989  ]
  [ 0.07593179  1.1028643 ]]

 [[ 0.7607697   0.17672282]
  [-2.668837    0.50430113]]], shape=(3, 2, 2), dtype=float32)


### Bài 13 & 14: Xây dựng Model tính toán (Tổng, Hiệu, Tích)

In [ ]:
import tensorflow as tf

# Bài 13: Model tính tổng
class SumModel(tf.Module):
    def __call__(self, x, y):
        return tf.add(x, y)

# Bài 14: Model tính hiệu và tích
class DiffProdModel(tf.Module):
    def __call__(self, x, y):
        diff = tf.subtract(x, y)
        prod = tf.multiply(x, y)
        return diff, prod

# Kiểm tra:
x = tf.constant([10.0, 20.0])
y = tf.constant([5.0, 5.0])

sum_model = SumModel()
diff_prod_model = DiffProdModel()

print("Tổng:", sum_model(x, y).numpy())
d, p = diff_prod_model(x, y)
print("Hiệu:", d.numpy(), "| Tích:", p.numpy())

Tổng: [15. 25.]
Hiệu: [ 5. 15.] | Tích: [ 50. 100.]


### Bài 15: Xây dựng Model tính chu vi hình chữ nhật

In [ ]:
class RectanglePerimeterModel(tf.Module):
    def __call__(self, a, b):
        return (a + b) * 2

# Kiểm tra:
rect_model = RectanglePerimeterModel()
a = tf.constant(5.0)
b = tf.constant(3.0)
print("Chu vi hình chữ nhật:", rect_model(a, b).numpy())

Chu vi hình chữ nhật: 16.0


### Bài 16: Xây dựng Model tính diện tích toàn phần hình hộp chữ nhật

In [ ]:
class BoxAreaModel(tf.Module):
    def __call__(self, a, b, c):
        s_xung_quanh = (a + b) * c * 2
        s_toan_phan = (a * b) * 2 + s_xung_quanh
        return s_xung_quanh, s_toan_phan

# Kiểm tra:
box_model = BoxAreaModel()
a = tf.constant(3.0)
b = tf.constant(4.0)
c = tf.constant(5.0)
sxq, stp = box_model(a, b, c)

print(f"Diện tích xung quanh: {sxq.numpy()}")
print(f"Diện tích toàn phần: {stp.numpy()}")

Diện tích xung quanh: 70.0
Diện tích toàn phần: 94.0
